"""Small-config hyperparameters for PeakSetSIGReg training step benchmark.

This file is READ-ONLY — do not modify.
"""

import torch

# Model architecture
MODEL_DIM = 512
NUM_LAYERS = 12
NUM_HEADS = 8
NUM_KV_HEADS = 8
ATTENTION_MLP_MULTIPLE = 4.0
FEATURE_MLP_HIDDEN_DIM = 128
MASKED_LATENT_PREDICTOR_NUM_LAYERS = 4
NORM_TYPE = "layernorm"
ENCODER_USE_ROPE = True
ENCODER_QK_NORM = False

# Data
BATCH_SIZE = 256
NUM_PEAKS = 64
AUTOCAST_DTYPE = torch.bfloat16

# JEPA / masking
JEPA_NUM_TARGET_BLOCKS = 2
CONTEXT_FRACTION = 0.3
TARGET_FRACTION = 0.25
MASKED_TOKEN_LOSS_WEIGHT = 1.0
MASKED_TOKEN_LOSS_TYPE = "l2"
REPRESENTATION_REGULARIZER = "none"

# Teacher EMA
USE_EMA_TEACHER_TARGET = True
TEACHER_EMA_DECAY = 1.0
TEACHER_EMA_DECAY_START = 0.996
TEACHER_EMA_DECAY_WARMUP_STEPS = 400_000
TEACHER_EMA_UPDATE_EVERY = 10

# Optimizer
LEARNING_RATE = 3e-4
WEIGHT_DECAY = 1e-5
B2 = 0.98
GRAD_CLIP_NORM = 1.0
MUON_MOMENTUM = 0.95
MUON_NESTEROV = True
MUON_NS_STEPS = 5
MUON_ADJUST_LR_FN = "match_rms_adamw"

# Training
SEED = 42
N_STEPS = 20
TOTAL_STEPS = 100_000
